version: '3.8'

services:
  plex-library-cleanup:
    build: .
    container_name: plex-library-cleanup
    restart: always
    ports:
      - "6064:6064"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
